import { defineField, defineType } from 'sanity'

export const journeyStage = defineType({
  name: 'journeyStage',
  title: 'Journey Stage',
  type: 'document',
  groups: [
    { name: 'content', title: 'Content', default: true },
    { name: 'extras', title: 'Extras' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'stageNumber',
      title: 'Stage Number',
      type: 'number',
      description: '1–8. Controls display order and JSON-LD step position.',
      validation: (Rule) => Rule.required().min(1).max(8).integer(),
      group: 'content',
    }),
    defineField({
      name: 'title_ka',
      title: 'Stage Name (Georgian)',
      type: 'string',
      validation: (Rule) => Rule.required(),
      group: 'content',
    }),
    defineField({
      name: 'title_en',
      title: 'Stage Name (English)',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'subtitle_ka',
      title: 'Subtitle (Georgian)',
      type: 'string',
      description: 'Optional short tagline shown next to the title.',
      group: 'content',
    }),
    defineField({
      name: 'subtitle_en',
      title: 'Subtitle (English)',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'duration_ka',
      title: 'Duration (Georgian)',
      type: 'string',
      description: 'e.g. "35–45 წუთი"',
      group: 'content',
    }),
    defineField({
      name: 'duration_en',
      title: 'Duration (English)',
      type: 'string',
      description: 'e.g. "35–45 minutes"',
      group: 'content',
    }),
    defineField({
      name: 'deliveredBy_ka',
      title: 'Delivered By (Georgian)',
      type: 'string',
      description: 'e.g. "ექთანი"',
      group: 'content',
    }),
    defineField({
      name: 'deliveredBy_en',
      title: 'Delivered By (English)',
      type: 'string',
      description: 'e.g. "Care Nurse"',
      group: 'content',
    }),
    defineField({
      name: 'body_ka',
      title: 'Stage Description (Georgian)',
      type: 'array',
      of: [{ type: 'block' }],
      description: '80–120 words.',
      validation: (Rule) => Rule.required(),
      group: 'content',
    }),
    defineField({
      name: 'body_en',
      title: 'Stage Description (English)',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'content',
    }),
    defineField({
      name: 'included_ka',
      title: "What's Included (Georgian)",
      type: 'array',
      of: [{ type: 'string' }],
      description: '2–6 specifics: assessments, tests, what the patient experiences.',
      validation: (Rule) => Rule.max(6),
      group: 'content',
    }),
    defineField({
      name: 'included_en',
      title: "What's Included (English)",
      type: 'array',
      of: [{ type: 'string' }],
      validation: (Rule) => Rule.max(6),
      group: 'content',
    }),
    defineField({
      name: 'deliverable_ka',
      title: 'Deliverable (Georgian)',
      type: 'string',
      description: 'Optional. e.g. "Healthspan Snapshot ანგარიში".',
      group: 'content',
    }),
    defineField({
      name: 'deliverable_en',
      title: 'Deliverable (English)',
      type: 'string',
      description: 'Optional. e.g. "Personal Longevity Plan PDF".',
      group: 'content',
    }),
    defineField({
      name: 'relatedTechnologies',
      title: 'Related Technologies',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'technology' }] }],
      description:
        'Drives in-body tech links and nested MedicalProcedure JSON-LD for SEO-rich stages.',
      group: 'extras',
    }),
    // Legacy free-text tools, kept for back-compat with existing content.
    defineField({
      name: 'tools',
      title: 'Tools (legacy free-text)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'extras',
    }),
    defineField({
      name: 'icon',
      title: 'Icon name (Lucide)',
      type: 'string',
      group: 'extras',
    }),
    defineField({
      name: 'seoKeywords',
      title: 'SEO Keywords (editorial reference)',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Editorial-only. Not rendered on the page.',
      group: 'seo',
    }),
  ],
  orderings: [
    {
      title: 'Stage Number',
      name: 'stageNumberAsc',
      by: [{ field: 'stageNumber', direction: 'asc' }],
    },
  ],
  preview: {
    select: {
      stageNumber: 'stageNumber',
      title_en: 'title_en',
      title_ka: 'title_ka',
      subtitle: 'subtitle_en',
    },
    prepare: ({ stageNumber, title_en, title_ka, subtitle }) => {
      const n = typeof stageNumber === 'number' ? String(stageNumber).padStart(2, '0') : '-'
      return {
        title: `${n} - ${title_en || title_ka || 'Untitled stage'}`,
        subtitle: subtitle ?? '',
      }
    },
  },
})

export const journeyPage = defineType({
  name: 'journeyPage',
  title: 'Patient Journey Page',
  type: 'document',
  // @ts-expect-error __experimental_actions is valid in Studio but not yet typed
  __experimental_actions: ['update', 'publish'],
  groups: [
    { name: 'hero', title: 'Hero', default: true },
    { name: 'cta', title: 'Closing CTA' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'eyebrow_ka',
      title: 'Hero Eyebrow (Georgian)',
      type: 'string',
      description: 'e.g. "პაციენტის გზა"',
      group: 'hero',
    }),
    defineField({
      name: 'eyebrow_en',
      title: 'Hero Eyebrow (English)',
      type: 'string',
      description: 'e.g. "Patient Journey"',
      group: 'hero',
    }),
    defineField({
      name: 'h1_ka',
      title: 'Heading H1 (Georgian)',
      type: 'string',
      validation: (Rule) => Rule.required(),
      group: 'hero',
    }),
    defineField({
      name: 'h1_en',
      title: 'Heading H1 (English)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'intro_ka',
      title: 'Intro Paragraph (Georgian)',
      type: 'text',
      rows: 4,
      validation: (Rule) => Rule.min(80).max(600),
      group: 'hero',
    }),
    defineField({
      name: 'intro_en',
      title: 'Intro Paragraph (English)',
      type: 'text',
      rows: 4,
      validation: (Rule) => Rule.min(60).max(500),
      group: 'hero',
    }),
    defineField({
      name: 'hero_image',
      title: 'Hero Image',
      type: 'image',
      options: { hotspot: true },
      fields: [
        defineField({
          name: 'alt_ka',
          title: 'Alt text (Georgian)',
          type: 'string',
        }),
        defineField({
          name: 'alt_en',
          title: 'Alt text (English)',
          type: 'string',
        }),
      ],
      group: 'hero',
    }),
    defineField({
      name: 'ctaHeading_ka',
      title: 'Closing CTA Eyebrow (Georgian)',
      type: 'string',
      group: 'cta',
    }),
    defineField({
      name: 'ctaHeading_en',
      title: 'Closing CTA Eyebrow (English)',
      type: 'string',
      group: 'cta',
    }),
    defineField({
      name: 'ctaBody_ka',
      title: 'Closing CTA Statement (Georgian)',
      type: 'text',
      rows: 2,
      group: 'cta',
    }),
    defineField({
      name: 'ctaBody_en',
      title: 'Closing CTA Statement (English)',
      type: 'text',
      rows: 2,
      group: 'cta',
    }),
    defineField({
      name: 'primaryCtaLabel_ka',
      title: 'Primary CTA Label (Georgian)',
      type: 'string',
      group: 'cta',
    }),
    defineField({
      name: 'primaryCtaLabel_en',
      title: 'Primary CTA Label (English)',
      type: 'string',
      group: 'cta',
    }),
    defineField({
      name: 'secondaryCtaLabel_ka',
      title: 'Secondary CTA Label (Georgian)',
      type: 'string',
      group: 'cta',
    }),
    defineField({
      name: 'secondaryCtaLabel_en',
      title: 'Secondary CTA Label (English)',
      type: 'string',
      group: 'cta',
    }),
    defineField({
      name: 'seo_title_ka',
      title: 'SEO Title (Georgian)',
      type: 'string',
      validation: (Rule) => Rule.max(70),
      group: 'seo',
    }),
    defineField({
      name: 'seo_title_en',
      title: 'SEO Title (English)',
      type: 'string',
      validation: (Rule) => Rule.max(70),
      group: 'seo',
    }),
    defineField({
      name: 'seo_description_ka',
      title: 'SEO Meta Description (Georgian)',
      type: 'text',
      rows: 2,
      validation: (Rule) => Rule.max(160),
      group: 'seo',
    }),
    defineField({
      name: 'seo_description_en',
      title: 'SEO Meta Description (English)',
      type: 'text',
      rows: 2,
      validation: (Rule) => Rule.max(160),
      group: 'seo',
    }),
  ],
  preview: {
    prepare: () => ({ title: 'Patient Journey Page' }),
  },
})
